name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            zip unzip python3-pip \
            autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev libncursesw5-dev \
            cmake libffi-dev libssl-dev \
            git wget

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install buildozer cython==0.29.33

      - name: Accept licenses
        run: yes | sdkmanager --licenses

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: medical-records-apk
          path: bin/*.apk
